country=US
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

# Higher priority = preferred when multiple networks are in range
network={
    ssid="TMOBILE-693A"
    psk="8svtkb75frx"
    priority=95
}

network={
    ssid="BBOPHOUSE"
    psk="Simon.123"
    priority=30
}

network={
    ssid="Sean's iPhone"
    psk="mangomeow"
    priority=25
}

network={
    ssid="Sean iPhone"
    psk="mangomeow"
    priority=25
}

network={
    ssid="UCSD-GUEST"
    key_mgmt=NONE
    priority=10
}
